#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 mugi (https://github.com/notmugi)
#
# Installs katugen: syncs templates, generates ~/.config/matugen/config.toml
# from the Application registry below, installs scripts + Dolphin menu.
# Idempotent.
#
# shellcheck disable=SC2088  # literal "~" in markers/outputs is intentional

set -euo pipefail

# Paths -------------------------------------------------------------------
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

TEMPLATES_DIR="$XDG_CONFIG_HOME/matugen/templates"
CONFIG_FILE="$XDG_CONFIG_HOME/matugen/config.toml"

BIN_DIR="$HOME/.local/bin"
SCRIPT_DST="$BIN_DIR/matugen-generate.sh"

HELPER_DIR="$XDG_DATA_HOME/katugen"
APPLY_DST="$HELPER_DIR/template-apply.sh"

SERVICEMENU_DIR="$XDG_DATA_HOME/kio/servicemenus"
SERVICEMENU_DST="$SERVICEMENU_DIR/matugen-generate.desktop"

STAMP="$(date +%Y%m%d%H%M%S)"

# Output ------------------------------------------------------------------
c_reset=$'\033[0m'; c_bold=$'\033[1m'; c_dim=$'\033[2m'
c_blue=$'\033[34m'; c_green=$'\033[32m'; c_yellow=$'\033[33m'; c_red=$'\033[31m'

info() { printf '%s==>%s %s\n'     "$c_blue"   "$c_reset" "$*"; }
ok()   { printf '%s  ✓%s %s\n'     "$c_green"  "$c_reset" "$*"; }
skip() { printf '%s  ·%s %s%s%s\n' "$c_dim"    "$c_reset" "$c_dim" "$*" "$c_reset"; }
warn() { printf '%s  !%s %s\n'     "$c_yellow" "$c_reset" "$*"; }
err()  { printf '%s ✗%s %s\n'      "$c_red"    "$c_reset" "$*" >&2; }

# Replace $dst with $src only if content differs; back up the original.
install_if_changed() {
    local src="$1" dst="$2" mode="${3:-0644}"
    mkdir -p "$(dirname "$dst")"
    if [[ -f "$dst" ]] && cmp -s "$src" "$dst"; then
        skip "unchanged: $dst"; chmod "$mode" "$dst"; return 0
    fi
    if [[ -e "$dst" || -L "$dst" ]]; then
        mv -- "$dst" "${dst}.bak-${STAMP}"
        warn "backed up old version → ${dst}.bak-${STAMP}"
    fi
    install -m "$mode" "$src" "$dst"
    ok "wrote $dst"
}

# Registry helpers --------------------------------------------------------
tmp_config=""
enabled=0
skipped=0
enabled_names=()

# Emit a [templates.<id>] block to $tmp_config.
register() {
    local id="$1" rel="$2" out="$3" hook="${4:-}"
    local src="$TEMPLATES_DIR/$rel"
    if [[ ! -f "$src" ]]; then
        warn "Template missing in repo: $rel (skipping $id)"
        skipped=$((skipped+1)); return 0
    fi

    mkdir -p "$(dirname "${out/#\~/$HOME}")"

    {
        printf '\n[templates.%s]\n' "$id"
        printf "input_path  = '%s/%s'\n" "$TEMPLATES_DIR" "$rel"
        printf "output_path = '%s'\n" "$out"
        if [[ -n "$hook" ]]; then
            printf "post_hook   = '%s'\n" "${hook//\'/\'\\\'\'}"
        fi
    } >> "$tmp_config"
    enabled_names+=("$id"); enabled=$((enabled+1))
}

# Register only if <marker> (file or directory) exists.
add_if() {
    local marker="$1"; shift
    if [[ -e "${marker/#\~/$HOME}" ]]; then register "$@"; else skipped=$((skipped+1)); fi
}

# Register both Noctalia Discord themes for a single client.
add_discord_if() {
    local marker="$1" client="$2"
    if [[ -e "${marker/#\~/$HOME}" ]]; then
        register "discord-material-$client" discord-material.css \
                 "$marker/themes/matugen-material.theme.css"
        register "discord-midnight-$client" discord-midnight.css \
                 "$marker/themes/matugen-midnight.theme.css"
    else
        skipped=$((skipped+2))
    fi
}

# Preflight ---------------------------------------------------------------
info "Checking prerequisites"
for c in matugen realpath; do
    command -v "$c" >/dev/null 2>&1 || { err "Missing: $c"; exit 1; }
done
ok "matugen $(matugen --version 2>&1 | head -1)"

command -v plasma-apply-colorscheme >/dev/null 2>&1 || \
    warn "plasma-apply-colorscheme not found — KDE auto-apply will be skipped at runtime."
command -v kbuildsycoca6 >/dev/null 2>&1 || command -v kbuildsycoca5 >/dev/null 2>&1 || \
    warn "kbuildsycoca6/5 not found — Dolphin menu appears after next login."

# Sync templates ----------------------------------------------------------
info "Syncing templates → $TEMPLATES_DIR"
mkdir -p "$TEMPLATES_DIR"
if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "$REPO_DIR/templates/" "$TEMPLATES_DIR/"
else
    rm -rf "$TEMPLATES_DIR"; mkdir -p "$TEMPLATES_DIR"
    cp -r "$REPO_DIR/templates/." "$TEMPLATES_DIR/"
fi
ok "Templates synced"

# Build matugen config ----------------------------------------------------
info "Detecting installed apps → $CONFIG_FILE"

mkdir -p \
    "$XDG_DATA_HOME/color-schemes" \
    "$XDG_CACHE_HOME/wal" \
    "$XDG_CACHE_HOME/katugen/zen-browser" \
    "$BIN_DIR" "$SERVICEMENU_DIR" "$HELPER_DIR"

tmp_config="$(mktemp)"
trap 'rm -f "$tmp_config"' EXIT

cat > "$tmp_config" <<'EOF'
# Matugen configuration — generated by katugen install.sh
# Re-run install.sh after installing new apps to refresh.

[config]
EOF

# =========================================================================
# Application registry
#
#   register   <id> <template> <output> [post-hook]        - always
#   add_if     <marker> <id> <template> <output> [hook]    - if marker exists
#   add_discord_if <marker> <client>                       - both themes
#
# Markers use literal "~" — expanded by the helpers above. Output paths
# also use literal "~" — matugen expands them at runtime. Hooks may use
# $APPLY_DST and $KATUGEN_MODE (set by matugen-generate.sh).
# =========================================================================

# Always-on
register kcolorscheme kcolorscheme.colors \
         "~/.local/share/color-schemes/matugen.colors"
register pywalfox     pywalfox.json \
         "~/.cache/wal/colors.json" \
         "$APPLY_DST pywalfox \"\$KATUGEN_MODE\""

# GTK
add_if "~/.config/gtk-3.0" gtk3 gtk3.css "~/.config/gtk-3.0/matugen.css"
add_if "~/.config/gtk-4.0" gtk4 gtk4.css "~/.config/gtk-4.0/matugen.css" \
       "$APPLY_DST gtk \"\$KATUGEN_MODE\""

# Qt
add_if "~/.config/qt5ct" qt5ct qtct.conf "~/.config/qt5ct/colors/matugen.conf"
add_if "~/.config/qt6ct" qt6ct qtct.conf "~/.config/qt6ct/colors/matugen.conf"

# Terminals
add_if "~/.config/alacritty" alacritty terminal/alacritty.toml \
       "~/.config/alacritty/themes/matugen.toml" "$APPLY_DST alacritty"
add_if "~/.config/foot"      foot     terminal/foot \
       "~/.config/foot/themes/matugen"          "$APPLY_DST foot"
add_if "~/.config/ghostty"   ghostty  terminal/ghostty \
       "~/.config/ghostty/themes/matugen"       "$APPLY_DST ghostty"
add_if "~/.config/kitty"     kitty    terminal/kitty.conf \
       "~/.config/kitty/themes/matugen.conf"    "$APPLY_DST kitty"
add_if "~/.config/wezterm"   wezterm  terminal/wezterm.toml \
       "~/.config/wezterm/colors/Matugen.toml"  "$APPLY_DST wezterm"

# Shell prompt — palette block spliced into starship.toml between markers.
add_if "~/.config/starship.toml" starship terminal/starship.toml \
       "~/.cache/katugen/starship-palette.toml" "$APPLY_DST starship"

# TUI apps
add_if "~/.config/btop"        btop    btop.theme \
       "~/.config/btop/themes/matugen.theme"     "$APPLY_DST btop"
add_if "~/.config/cava/config" cava    cava.ini \
       "~/.config/cava/themes/matugen"           "$APPLY_DST cava"
add_if "~/.config/helix"       helix   helix.toml \
       "~/.config/helix/themes/matugen.toml"
add_if "~/.config/yazi"        yazi    yazi.toml \
       "~/.config/yazi/flavors/matugen.yazi/flavor.toml" "$APPLY_DST yazi"
add_if "~/.config/zathura"     zathura zathurarc \
       "~/.config/zathura/matugenrc"             "$APPLY_DST zathura"

# Editors
add_if "~/.config/zed"   zed   zed.json   "~/.config/zed/themes/matugen.json"
add_if "~/.config/emacs" emacs emacs.el   "~/.config/emacs/matugen-theme.el"

# Discord clients (both Noctalia themes per detected client)
add_discord_if "~/.config/vesktop"                                vesktop
add_discord_if "~/.config/BetterDiscord"                          bd
add_discord_if "~/.config/webcord"                                webcord
add_discord_if "~/.config/armcord"                                armcord
add_discord_if "~/.config/equibop"                                equibop
add_discord_if "~/.config/Equicord"                               equicord
add_discord_if "~/.config/Vencord"                                vencord
add_discord_if "~/.var/app/com.discordapp.Discord/config/Vencord" vencord-flatpak
add_discord_if "~/.config/dorion"                                 dorion
add_discord_if "~/.config/lightcord"                              lightcord

# Spicetify (overwrites Comfy theme's color.ini)
add_if "~/.config/spicetify/Themes/Comfy" spicetify spicetify.ini \
       "~/.config/spicetify/Themes/Comfy/color.ini" \
       "spicetify -q apply --no-restart"

# Telegram Desktop
add_if "~/.config/telegram-desktop" telegram telegram.tdesktop-theme \
       "~/.config/telegram-desktop/themes/matugen.tdesktop-theme"

# Steam (Material-Theme skin must be installed separately)
add_if "~/.steam/steam/steamui/skins/Material-Theme" steam steam.css \
       "~/.steam/steam/steamui/skins/Material-Theme/css/main/colors/matugen.css"

# Wayland compositors
add_if "~/.config/hypr/hyprland.conf" hyprland     hyprland.conf \
       "~/.config/hypr/matugen/matugen-colors.conf"
add_if "~/.config/hypr/hyprland.conf" hyprland-lua hyprland.lua \
       "~/.config/hypr/matugen/matugen-colors.lua" "$APPLY_DST hyprland"
add_if "~/.config/hyprtoolkit"        hyprtoolkit  hyprtoolkit.conf \
       "~/.config/hypr/hyprtoolkit.conf"
add_if "~/.config/niri/config.kdl"    niri         niri.kdl \
       "~/.config/niri/matugen.kdl"               "$APPLY_DST niri"
add_if "~/.config/sway/config"        sway         sway \
       "~/.config/sway/matugen"                   "$APPLY_DST sway"
add_if "~/.config/labwc/rc.xml"       labwc        labwc.conf \
       "~/.config/labwc/themerc-override"         "$APPLY_DST labwc"
add_if "~/.config/mango/config.conf"  mango        mango.conf \
       "~/.config/mango/matugen.conf"             "$APPLY_DST mango"
add_if "~/.config/scroll/config"      scroll       scroll \
       "~/.config/scroll/matugen"                 "$APPLY_DST scroll"

# App launchers
add_if "~/.config/fuzzel"             fuzzel  fuzzel.conf \
       "~/.config/fuzzel/themes/matugen"          "$APPLY_DST fuzzel"
add_if "~/.config/walker/config.toml" walker  walker.css \
       "~/.config/walker/themes/matugen/style.css" "$APPLY_DST walker"
add_if "~/.local/share/vicinae"       vicinae vicinae.toml \
       "~/.local/share/vicinae/themes/matugen.toml" "vicinae theme set matugen"

# Noctalia shell
add_if "~/.config/noctalia" noctalia noctalia.json "~/.config/noctalia/colors.json"

# Zen Browser — staged in cache; post-hook auto-imports into profiles.
add_if "~/.zen" zen-userchrome zen-browser/zen-userChrome.css \
       "~/.cache/katugen/zen-browser/zen-userChrome.css"
add_if "~/.zen" zen-usercontent zen-browser/zen-userContent.css \
       "~/.cache/katugen/zen-browser/zen-userContent.css" \
       "$APPLY_DST zen"

# =========================================================================

install_if_changed "$tmp_config" "$CONFIG_FILE" 0644

ok "Enabled $enabled templates:"
printf '       %s\n' "${enabled_names[@]}" | column -c 80 \
    || printf '       %s\n' "${enabled_names[@]}"
[[ $skipped -gt 0 ]] && skip "Skipped $skipped (app not detected — install and re-run)"

# Install scripts ---------------------------------------------------------
info "Installing helper script → $HELPER_DIR"
install_if_changed "$REPO_DIR/scripts/template-apply.sh" "$APPLY_DST" 0755

info "Installing generator script → $SCRIPT_DST"
install_if_changed "$REPO_DIR/scripts/matugen-generate.sh" "$SCRIPT_DST" 0755
case ":$PATH:" in
    *":$BIN_DIR:"*) : ;;
    *) warn "$BIN_DIR is not in your PATH (fine for the Dolphin menu)." ;;
esac

# Install Dolphin service menu --------------------------------------------
info "Installing Dolphin service menu → $SERVICEMENU_DST"
rendered="$(mktemp)"
sed "s|@SCRIPT@|${SCRIPT_DST}|g" \
    "$REPO_DIR/servicemenus/matugen-generate.desktop" > "$rendered"
install_if_changed "$rendered" "$SERVICEMENU_DST" 0755
rm -f "$rendered"

info "Rebuilding KIO service cache"
if command -v kbuildsycoca6 >/dev/null 2>&1; then
    kbuildsycoca6 --noincremental >/dev/null 2>&1 || true; ok "kbuildsycoca6 done"
elif command -v kbuildsycoca5 >/dev/null 2>&1; then
    kbuildsycoca5 --noincremental >/dev/null 2>&1 || true; ok "kbuildsycoca5 done"
else
    warn "Skipped (no kbuildsycoca found)"
fi

cat <<EOF

${c_bold}${c_green}katugen installed.${c_reset}

Right-click an image in Dolphin → ${c_bold}Generate${c_reset} → ${c_bold}Light${c_reset} or ${c_bold}Dark${c_reset}.
Re-run this script after installing new apps to pick them up.

Logs: ${XDG_CACHE_HOME}/matugen-generate.log
EOF
